# Generated by Django 4.1.1 on 2022-10-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='janariak',
            name='submota',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
