# Generated by Django 4.1.1 on 2022-11-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janaria', '0002_janariak_submota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janariak',
            name='osagaiak',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
