# Generated by Django 4.1.1 on 2022-11-09 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bezeroak',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('telefono_zenbakia', models.CharField(max_length=9, null=True)),
                ('posta_kodea', models.CharField(max_length=5, null=True)),
                ('herria', models.CharField(max_length=50, null=True)),
                ('probintzia', models.CharField(max_length=50, null=True)),
                ('id_erabiltzaile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
