# Generated by Django 4.1.1 on 2022-10-26 06:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezeroak',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('telefono_zenbakia', models.IntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(9)])),
                ('posta_kodea', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(5)])),
                ('herria', models.CharField(max_length=50)),
                ('probintzia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Erabiltzaileak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('last_login', models.CharField(max_length=50)),
                ('is_superuser', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('is_staff', models.CharField(max_length=50)),
                ('is_active', models.CharField(max_length=50)),
                ('date_joinded', models.CharField(max_length=50)),
                ('bezero_dni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bezeroa.bezeroak')),
            ],
        ),
    ]
