# Generated by Django 4.1.1 on 2022-11-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezeroa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezeroak',
            name='helbidea',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
