# Generated by Django 4.1.1 on 2022-10-28 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bezeroa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erabiltzaileak',
            name='bezero_dni',
        ),
        migrations.AddField(
            model_name='bezeroak',
            name='id_erabiltzaile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
