# Generated by Django 4.1.1 on 2022-11-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezeroa', '0002_bezeroak_helbidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezeroak',
            name='puntuak',
            field=models.IntegerField(null=True),
        ),
    ]
