# Generated by Django 4.1.1 on 2022-10-28 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezeroa', '0003_delete_erabiltzaileak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bezeroak',
            name='posta_kodea',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='bezeroak',
            name='telefono_zenbakia',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
