# Generated by Django 4.1.1 on 2022-10-28 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezeroa', '0006_alter_bezeroak_posta_kodea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bezeroak',
            name='telefono_zenbakia',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator('xxxxxxxxx')]),
        ),
    ]
