# Generated by Django 4.1.1 on 2022-10-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezeroa', '0009_alter_bezeroak_telefono_zenbakia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bezeroak',
            name='posta_kodea',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bezeroak',
            name='telefono_zenbakia',
            field=models.CharField(max_length=9),
        ),
    ]
