# Generated by Django 4.1.1 on 2022-11-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezeroa', '0010_alter_bezeroak_posta_kodea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bezeroak',
            name='herria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bezeroak',
            name='posta_kodea',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bezeroak',
            name='probintzia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bezeroak',
            name='telefono_zenbakia',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
