# Generated by Django 4.1.1 on 2022-10-26 06:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bezeroa', '0001_initial'),
        ('erosketa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Txartelak',
            fields=[
                ('zenbakia', models.IntegerField(primary_key=True, serialize=False)),
                ('iraungitze_data', models.DateField()),
                ('cvv', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)])),
                ('bezero_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bezeroa.bezeroak')),
            ],
        ),
        migrations.CreateModel(
            name='Bidalketak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eguna', models.DateField(null=True)),
                ('ordua', models.DateTimeField(null=True)),
                ('helbidea', models.CharField(max_length=50)),
                ('erosketa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erosketa.erosketak')),
            ],
        ),
    ]
