# Generated by Django 4.1.1 on 2022-10-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidalketa', '0002_alter_txartelak_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txartelak',
            name='iraungitze_data',
            field=models.DateField(verbose_name=['%m-%Y']),
        ),
    ]
