# Generated by Django 4.1.1 on 2022-10-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidalketa', '0003_alter_txartelak_iraungitze_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txartelak',
            name='iraungitze_data',
            field=models.DateField(verbose_name='10-2022'),
        ),
    ]
