# Generated by Django 4.1.1 on 2022-10-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidalketa', '0004_alter_txartelak_iraungitze_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txartelak',
            name='iraungitze_data',
        ),
    ]
