# Generated by Django 4.1.1 on 2022-10-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidalketa', '0005_remove_txartelak_iraungitze_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='txartelak',
            name='iraungitze_data',
            field=models.DateField(null=True),
        ),
    ]
