# Generated by Django 4.1.1 on 2022-11-02 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidalketa', '0006_txartelak_iraungitze_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txartelak',
            name='iraungitze_data',
            field=models.CharField(help_text='format: mm/aaaa', max_length=7, validators=[django.core.validators.RegexValidator('^\\d\\d/\\d\\d\\d\\d', message='Wrong format enter')]),
        ),
    ]
