# Generated by Django 4.1.1 on 2022-11-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidalketa', '0007_alter_txartelak_iraungitze_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidalketak',
            name='ordua',
            field=models.TimeField(null=True),
        ),
    ]
