# Generated by Django 4.1.1 on 2022-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidalketa', '0008_alter_bidalketak_ordua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txartelak',
            name='zenbakia',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
