# Generated by Django 4.1.1 on 2022-11-09 07:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('janaria', '0001_initial'),
        ('bezeroa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erosketak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eguna', models.DateField(null=True)),
                ('ordua', models.TimeField(null=True)),
                ('ordaintzeko_guztira', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bukatuta', models.BooleanField(null=True)),
                ('bezero_dni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bezeroa.bezeroak')),
            ],
        ),
        migrations.CreateModel(
            name='Saskiak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kantitate_kopurua', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('guztira', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('erosketa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erosketa.erosketak')),
                ('janari_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janaria.janariak')),
            ],
        ),
    ]
