# Generated by Django 4.1.1 on 2022-11-14 09:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bezeroa', '0003_bezeroak_puntuak'),
        ('erosketa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Txartelak',
            fields=[
                ('zenbakia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titularra', models.CharField(max_length=100, null=True)),
                ('iraungitze_data', models.CharField(help_text='format: mm/aaaa', max_length=7, validators=[django.core.validators.RegexValidator('^\\d\\d/\\d\\d\\d\\d', message='Wrong format enter')])),
                ('cvv', models.CharField(max_length=3)),
                ('bezero_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bezeroa.bezeroak')),
            ],
        ),
        migrations.CreateModel(
            name='Bidalketak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eguna', models.DateField(null=True)),
                ('ordua', models.TimeField(null=True)),
                ('helbidea', models.CharField(max_length=50)),
                ('erosketa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erosketa.erosketak')),
            ],
        ),
    ]
