# Generated by Django 4.1.1 on 2022-11-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosketa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saskiak',
            name='guztira',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
