# Generated by Django 4.1.1 on 2022-11-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erosketa', '0002_saskiak_guztira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erosketak',
            name='saskia_id',
        ),
        migrations.AddField(
            model_name='saskiak',
            name='erosketa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erosketa.erosketak'),
        ),
    ]
