# Generated by Django 4.1.1 on 2022-11-14 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosketa', '0002_txartelak_bidalketak'),
    ]

    operations = [
        migrations.AddField(
            model_name='erosketak',
            name='totala',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
