# Generated by Django 4.1.1 on 2022-11-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosketa', '0003_remove_erosketak_saskia_id_saskiak_erosketa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erosketak',
            name='ordua',
            field=models.TimeField(null=True),
        ),
    ]
