# Generated by Django 4.1.1 on 2022-11-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosketa', '0003_erosketak_totala'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidalketak',
            name='herria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bidalketak',
            name='kostua',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bidalketak',
            name='probintzia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bidalketak',
            name='helbidea',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
