# Generated by Django 4.1.1 on 2022-11-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosketa', '0004_alter_erosketak_ordua'),
    ]

    operations = [
        migrations.AddField(
            model_name='erosketak',
            name='session_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
