# Generated by Django 4.1.1 on 2022-11-07 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosketa', '0005_erosketak_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erosketak',
            name='ordaintzeko_guztira',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
