# Generated by Django 4.1.1 on 2022-11-07 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosketa', '0006_alter_erosketak_ordaintzeko_guztira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erosketak',
            name='ordaintzeko_guztira',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
